package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-11-27T12:57:54.418-05:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "ConsultaReniec",
                  wsdlLocation = "file:/C:/Users/ldavilan/Documents/servicios/PRIMA%20CORE%20SERVICES/op-reniec-soap/src/main/resources/wsdl/ConsultaReniec.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class ConsultaReniec extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ConsultaReniec");
    public final static QName ConsultaReniecSoap = new QName("http://tempuri.org/", "ConsultaReniecSoap");
    public final static QName ConsultaReniecSoap12 = new QName("http://tempuri.org/", "ConsultaReniecSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ldavilan/Documents/servicios/PRIMA%20CORE%20SERVICES/op-reniec-soap/src/main/resources/wsdl/ConsultaReniec.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaReniec.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ldavilan/Documents/servicios/PRIMA%20CORE%20SERVICES/op-reniec-soap/src/main/resources/wsdl/ConsultaReniec.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaReniec(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaReniec(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaReniec() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ConsultaReniec(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaReniec(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaReniec(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ConsultaReniecSoap
     */
    @WebEndpoint(name = "ConsultaReniecSoap")
    public ConsultaReniecSoap getConsultaReniecSoap() {
        return super.getPort(ConsultaReniecSoap, ConsultaReniecSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaReniecSoap
     */
    @WebEndpoint(name = "ConsultaReniecSoap")
    public ConsultaReniecSoap getConsultaReniecSoap(WebServiceFeature... features) {
        return super.getPort(ConsultaReniecSoap, ConsultaReniecSoap.class, features);
    }


    /**
     *
     * @return
     *     returns ConsultaReniecSoap
     */
    @WebEndpoint(name = "ConsultaReniecSoap12")
    public ConsultaReniecSoap getConsultaReniecSoap12() {
        return super.getPort(ConsultaReniecSoap12, ConsultaReniecSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaReniecSoap
     */
    @WebEndpoint(name = "ConsultaReniecSoap12")
    public ConsultaReniecSoap getConsultaReniecSoap12(WebServiceFeature... features) {
        return super.getPort(ConsultaReniecSoap12, ConsultaReniecSoap.class, features);
    }

}
