package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2023-11-24T15:07:01.665-05:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ConsultaReniecSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ConsultaReniecSoap {

    @WebMethod(operationName = "ConsultaXNombres", action = "http://tempuri.org/ConsultaXNombres")
    @RequestWrapper(localName = "ConsultaXNombres", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaXNombres")
    @ResponseWrapper(localName = "ConsultaXNombresResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultaXNombresResponse")
    @WebResult(name = "ConsultaXNombresResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RespNombres consultaXNombres(
        @WebParam(name = "apellidoPaterno", targetNamespace = "http://tempuri.org/")
        java.lang.String apellidoPaterno,
        @WebParam(name = "apellidoMaterno", targetNamespace = "http://tempuri.org/")
        java.lang.String apellidoMaterno,
        @WebParam(name = "nombres", targetNamespace = "http://tempuri.org/")
        java.lang.String nombres,
        @WebParam(name = "inicio", targetNamespace = "http://tempuri.org/")
        java.lang.String inicio,
        @WebParam(name = "cant", targetNamespace = "http://tempuri.org/")
        int cant,
        @WebParam(name = "datosAuditoria", targetNamespace = "http://tempuri.org/")
        org.tempuri.DatosAuditoria datosAuditoria
    );

    @WebMethod(operationName = "ConsultarDNI", action = "http://tempuri.org/ConsultarDNI")
    @RequestWrapper(localName = "ConsultarDNI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarDNI")
    @ResponseWrapper(localName = "ConsultarDNIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConsultarDNIResponse")
    @WebResult(name = "ConsultarDNIResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.RespDNI consultarDNI(
        @WebParam(name = "DNI", targetNamespace = "http://tempuri.org/")
        java.lang.String dni,
        @WebParam(name = "datosAuditoria", targetNamespace = "http://tempuri.org/")
        org.tempuri.DatosAuditoria datosAuditoria
    );
}
